//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//EULER PROJECT 02

public class evenfibo 
{

	public static void main(String[] args)  
	{
		// TODO Auto-generated method stub
		int a=0,b=1,c=0,s=0;
		while(c<4000000)
		{
			c=a+b;
			a=b;
			b=c;
			if(c%2==0)
			{
				s+=c;
			}
		}
		System.out.println("sum = "+s);

	}

}
